# respostas.py

# Mensagens de boas-vindas
respostas_iniciais = [
    "Olá, sou seu assistente de RH. Em que posso ajudá-lo?",
    "Oi! Estou aqui para ajudar com qualquer informação sobre nossos processos de RH. Como posso ajudar?",
    "Olá! Sou o assistente de RH. Precisa de informações sobre vagas ou processos seletivos?",
    "Bem-vindo! Posso ajudá-lo a encontrar informações sobre as vagas em aberto ou algo relacionado a RH?",
    "Oi! Em que posso ajudar hoje com relação aos processos de RH e vagas?"

]

#keywords para listar vagas
keywords_listavagas = [
    "ver nossas vagas",
    "queria saber quais sao as nossas vagas"
    "ver vagas",
    "quais sao as nossas vagas",
    "quais são as vagas",
    "quais vagas estão disponíveis",
    "quais vagas estão abertas",
    "quais vagas estão em aberto",
    "quais vagas temos",
    "quais vagas estão disponíveis",
    "quero ver nossas vagas",
    "temos vagas de que?",
    "quero saber sobre nossas vagas",
    "poderia listar as vagas?",
    "gostaria de ver as vagas",
    "o que temos de vagas?",
    "quais as vagas?",
    "me mostra as vagas",
    "tem vagas abertas?",
    "lista de vagas",
    "quais vagas temos abertas?",
    "nossos processos",
    "processos de recrutamento",
    "mostrar vagas",
    "lista completa de vagas",
    "ver oportunidades",
    "quero ver os processos seletivos",
    "quero saber sobre os processos seletivos",
    "tem algum processo seletivo?",
    "quais são os processos seletivos?",
    "me fale sobre as oportunidades",
    "posso ver os processos?",
    "quero conhecer as vagas disponíveis",
    "pode listar as oportunidades?",
    "existem vagas disponíveis?",
    "pode me mostrar os processos?",
    "ver as oportunidades atuais",
    "processos seletivos em aberto",
    "quais vagas estão abertas atualmente?",
    "pode mostrar as vagas em aberto?",
    "quais são as oportunidades disponíveis?",
    "tem algum cargo em aberto?",
    "temos alguma vaga para aplicar?",
    "há algum processo ativo?",
    "você pode listar os processos atuais?",
    "me informe as vagas",
    "gostaria de ver as oportunidades atuais",
    "me fale sobre as posições abertas",
    "quais outras vagas temos?",
    "me mostre nossas vagas",
    "quero visualizar as vagas",
    "quais são as vagas em aberto?",
    "tem alguma posição disponível?",
    "me diga as vagas disponíveis",
    "há alguma vaga aberta?",
    "quero saber sobre os cargos em aberto",
    "pode listar os cargos disponíveis?",
    "mostrar todas as vagas",
    "você tem informações sobre vagas?",
    "ver lista de vagas",
    "ver posições disponíveis",
    "quero detalhes das vagas abertas",
    "pode compartilhar as oportunidades?",
    "há algo aberto no momento?",
    "me mostre todas as posições abertas",
    "tem alguma posição ativa?",
    "queria saber quais vagas nós temos?",
    "quero saber quais sao as nossas vagas",
]


# respostas caso tenham vagas
respostas_confirmacao_abertos_geral = [
    "Temos sim! Há processos em aberto. Gostaria de mais detalhes?",
    "Sim, temos processos seletivos em aberto! Posso ajudar com mais informações?",
    "Sim, há vagas disponíveis no momento. Quer saber mais sobre alguma em específico?",
    "Temos sim! Existem oportunidades em aberto. Deseja ver a lista completa?",
    "Com certeza! Temos vagas em aberto. Posso listar para você?",
    "Sim, temos processos abertos. Gostaria de conferir os detalhes?",
    "Isso mesmo! Existem processos seletivos abertos. Quer saber mais?",
    "Sim, estamos com vagas abertas! Posso te mostrar quais são elas?"
]

#respostas para listar vagas
resposta_listavagas = [
    "Claro, aqui estão as vagas que estamos em aberto:",
    "Aqui está a lista das oportunidades atuais:",
    "Essas são as vagas disponíveis no momento:",
    "Veja abaixo os processos em aberto que temos atualmente:",
    "Aqui estão as oportunidades que estão abertas no momento:",
    "Qual dessas você gostaria de saber mais?"
]

perguntas_possiveis = [
    "Quer saber mais sobre essa vaga?",
    "Gostaria de ver um relatório detalhado desta vaga?",
    "Quer informações adicionais sobre esta oportunidade?",
    "Precisa de mais detalhes ou um relatório completo?",
    "Deseja ver dados de desempenho e métricas desta vaga?",
    "Gostaria que eu gerasse um relatório PDF com as informações desta vaga?",
    "Precisa de algo mais relacionado a esta vaga?",
    "Quer que eu explique os requisitos em mais detalhes?",
]


introducoes = [
        "Aqui estão os detalhes da vaga que você selecionou:",
        "Confira as informações completas sobre a vaga:",
        "Detalhes sobre a vaga escolhida:",
        "Segue uma descrição detalhada da vaga:",
        "Aqui estão as informações que você solicitou para esta vaga:"
    ]

# Respostas positivas
respostas_positivas = [
    "sim",
    "claro",
    "pode ser",
    "quero",
    "sim, por favor",
    "ok",
    "sim claro",
    "com certeza",
    "claro que sim",
    "sim, quero",
    "quero sim",
    "sim, por gentileza",
    "claro que quero",
    "pode enviar",
    "quero saber mais",
    "sim quero saber mais",
    "sim quero",
    "sim, desejo",
    "sim, estou interessado",
    "sim, faça isso",
    "sim, gostaria",
    "sim, por favor envie",
    "sim, por favor faça",
    "ok, pode fazer",
    "ok, faça isso",
    "sim, vá em frente",
    "claro, pode fazer",
    "claro, vá em frente",
    "sim, confirme",
    "sim, prossiga",
    "sim, estou de acordo",
    "sim, está correto",
    "sim, tudo bem",
    "sim, está certo",
    "certo, pode fazer",
    "isso mesmo, faça",
    "sim, sem dúvidas",
    "sim, eu quero",
    "sim, por favor envie",
    "ss",
    
]

# Respostas negativas
respostas_negativas = [
    "não", 
    "nao", 
    "não quero", 
    "não, obrigado", 
    "não, obrigada", 
    "não preciso", 
    "não estou interessado", 
    "não, não quero", 
    "não, não preciso", 
    "não desejo", 
    "não, agora não", 
    "não quero saber", 
    "não é necessário", 
    "não precisa", 
    "não, por enquanto não", 
    "não, talvez depois", 
    "não, estou bem", 
    "não, está ok", 
    "não, está certo assim", 
    "não quero nada", 
    "não quero relatório", 
    "não, deixa assim", 
    "não, está tudo certo", 
    "não, pode deixar", 
    "não, não faça", 
    "não, sem necessidade", 
    "não estou interessado no momento", 
    "não, está resolvido", 
    "não desejo mais informações", 
    "não, não estou interessado", 
    "não agora", 
    "não quero saber mais", 
    "não, pare", 
    "não, encerre", 
    "não, já resolvi", 
    "não, nada disso", 
    "não concordo", 
    "não, não precisa disso",
    
    # Respostas sem "não"
    "acho que não", 
    "não sei", 
    "talvez não", 
    "prefiro não", 
    "não por agora", 
    "deixa para depois", 
    "não faz sentido para mim",
    "acho que não é necessário",
    "não estou com interesse no momento",
    "talvez depois",
    "depois eu vejo",
    "deixa quieto",
    "não é o que estou buscando",
    "passo dessa vez",
    "estou satisfeito",
    "está bom assim",
    "agora não, obrigado",
    "já resolvi",
    "deixa assim mesmo",
    "pode parar",
    "pode encerrar",
    "tá tranquilo",
    "não precisa mexer nisso",
    "isso não é relevante",
    "já está ok para mim",
    "nada a ver",
    "isso não faz sentido para mim",
    "deixa pra lá",
    "não faz diferença",
    "pode esquecer isso",
    "não quero mais",
    "sem necessidade",
    "não me interessa",
    "não faz sentido",
    "está bem assim",
    "não é algo que eu preciso"
]

frases_buscar_vaga = [
    "quero ver a vaga de",
    "me mostre a vaga de",
    "gostaria de ver detalhes da vaga de",
    "mostre informações sobre a vaga de",
    "quais são os detalhes da vaga de",
    "quero informações da vaga de",
    "pode mostrar a vaga de",
    "me diga sobre a vaga de",
    "preciso de informações da vaga de",
    "gostaria de saber sobre a vaga de",
    "pode falar sobre a vaga de",
    "quero detalhes da vaga de",
    "qual é a descrição da vaga de",
    "explique mais sobre a vaga de",
    "me informe sobre a vaga de",
    "pode me mostrar os detalhes da vaga de",
    "quero saber a respeito da vaga de",
    "tenho interesse na vaga de",
    "o que tem na vaga de",
    "preciso saber sobre a vaga de",
    "mostre os dados da vaga de",
    "diga os detalhes da vaga de",
    "o que envolve a vaga de",
    "fale sobre a posição de",
    "gostaria de entender a vaga de",
    "há informações sobre a vaga de",
    "pode detalhar a vaga de",
    "me passe informações sobre a vaga de",
    "quais os requisitos para a vaga de",
    "quero saber a respeito da vaga de",
    "tem mais informações da vaga de"
]
